"""Strategy Comparison Tab — PPO vs baselines across all 4 scenarios.

Loads results/all_results.json (generated by run_training.py).
Shows:
- Grouped bar chart: Pr[goal] per strategy for the selected scenario
- DP benchmark horizontal line
- Full metrics table (pr_goal, pr_bankruptcy, median, p10, p90)
"""

from __future__ import annotations

import json
import pathlib
from typing import Any

import plotly.graph_objects as go
from shiny import module, reactive, render, ui
from shinywidgets import output_widget, render_widget

# ── Load results (once at import time if available) ───────────────────────────
_RESULTS_PATH = pathlib.Path(__file__).parents[4] / "results" / "all_results.json"

_STRATEGY_COLORS = {
    "PPO (RL)":     "#2c7bb6",
    "TDF":          "#abd9e9",
    "Aggressive":   "#d7191c",
    "Conservative": "#1a9641",
    "Moderate":     "#fdae61",
    "Greedy":       "#756bb1",
}

_SCENARIO_LABELS = {
    "base":       "Base Case",
    "young":      "Young Investor",
    "retirement": "Retirement",
    "stressed":   "Stressed",
}


def _load_results() -> dict | None:
    if _RESULTS_PATH.exists():
        with open(_RESULTS_PATH) as f:
            return json.load(f)
    return None


def _make_bar_chart(results: dict, scenario_key: str) -> go.Figure:
    scen   = results[scenario_key]
    strats = scen["strategies"]
    dp_pr  = scen["dp_pr_goal"]
    label  = _SCENARIO_LABELS.get(scenario_key, scenario_key)

    names  = list(strats.keys())
    values = [strats[s]["pr_goal"] for s in names]
    colors = [_STRATEGY_COLORS.get(s, "#999999") for s in names]

    fig = go.Figure()
    fig.add_trace(go.Bar(
        x=names,
        y=[v * 100 for v in values],
        marker_color=colors,
        text=[f"{v:.1%}" for v in values],
        textposition="outside",
        name="Pr[Goal]",
    ))

    # DP benchmark line
    fig.add_hline(
        y=dp_pr * 100,
        line_width=2, line_dash="dash", line_color="#d7191c",
        annotation_text=f"DP Benchmark {dp_pr:.1%}",
        annotation_position="top right",
        annotation_font_color="#d7191c",
    )

    fig.update_layout(
        title=f"Pr[Reach Goal] by Strategy — {label}",
        xaxis_title="Strategy",
        yaxis_title="Probability of Reaching Goal (%)",
        yaxis_range=[0, min(100, max(v * 100 for v in values) + 15)],
        template="plotly_white",
        height=460,
        showlegend=False,
    )
    return fig


def _make_metrics_table(results: dict, scenario_key: str):
    scen   = results[scenario_key]
    strats = scen["strategies"]

    rows = []
    for name, s in strats.items():
        rows.append({
            "Strategy":        name,
            "Pr[Goal]":        f"{s['pr_goal']:.1%}",
            "Pr[Bankruptcy]":  f"{s['pr_bankruptcy']:.1%}",
            "Median ($)":      f"${s['median']:>12,.0f}",
            "P10 ($)":         f"${s['p10']:>12,.0f}",
            "P90 ($)":         f"${s['p90']:>12,.0f}",
        })

    dp_pr = scen["dp_pr_goal"]
    rows.append({
        "Strategy":       "DP (paper benchmark)",
        "Pr[Goal]":       f"{dp_pr:.1%}",
        "Pr[Bankruptcy]": "—",
        "Median ($)":     "—",
        "P10 ($)":        "—",
        "P90 ($)":        "—",
    })
    return rows


# ── Shiny module ──────────────────────────────────────────────────────────────

@module.ui
def tab_strategy_comparison_ui(data_utils: dict[str, Any], data_inputs: dict[str, Any]) -> Any:
    results = _load_results()

    if results is None:
        return ui.div(
            ui.h3("Strategy Comparison", class_="mb-3 mt-2"),
            ui.div(
                ui.p("Results not yet available. Please run ", ui.code("python run_training.py"),
                     " from the project root to generate ", ui.code("results/all_results.json"), "."),
                class_="alert alert-warning",
            ),
        )

    scenario_choices = {k: _SCENARIO_LABELS.get(k, k) for k in results}

    return ui.div(
        ui.h3("Strategy Comparison", class_="mb-3 mt-2"),
        ui.p(
            "Compare PPO (RL) against benchmark strategies across all four investor scenarios. "
            "The dashed red line shows the DP optimum from Das et al. (2024).",
            class_="text-muted mb-4",
        ),
        ui.input_select(
            "scenario", "Select Scenario",
            choices=scenario_choices,
            selected="base",
        ),
        output_widget("plot_bars"),
        ui.br(),
        ui.h5("Full Metrics Table"),
        ui.output_table("metrics_table"),
    )


@module.server
def tab_strategy_comparison_server(
    input: Any, output: Any, session: Any,
    data_utils: dict[str, Any],
    data_inputs: dict[str, Any],
    reactives_shiny: Any,
) -> None:
    results = _load_results()

    @render_widget
    def plot_bars():
        if results is None:
            fig = go.Figure()
            fig.update_layout(title="No results — run training first", template="plotly_white", height=460)
            return fig
        return _make_bar_chart(results, input.scenario())

    @output
    @render.table
    def metrics_table():
        if results is None:
            import pandas as pd
            return pd.DataFrame({"Status": ["Run training to see results"]})
        import pandas as pd
        rows = _make_metrics_table(results, input.scenario())
        return pd.DataFrame(rows)
